/* this file was generated from the NETMAN file:
	define05.c
	07/09/98 15:09:12
*/
#define SUPER_USER
#include "petri.h"
#include "userfunc.h"
#include <stdlib.h>

#ifndef CONST_NET
#ifdef SEGMENTED_MEMORY
void DefineNet5()
{
NCTArc *parcInputs, *parcOutputs;

InitTransition( 55, "", 4, 2, 2, 3, 4, TF_1_7, NULL, NULL );
net.tran[55].number[1] = 0;
net.tran[55].number[2] = 18;
net.tran[55].number[3] = 7;
parcInputs = net.tran[55].inputArc;
parcOutputs = net.tran[55].outputArc;
InitArc( &parcInputs[0], 1, 86, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 99, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 162, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 91, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 56, "", 4, 2, 2, 3, 4, TF_1_8, NULL, NULL );
net.tran[56].number[1] = 0;
net.tran[56].number[2] = 18;
net.tran[56].number[3] = 8;
parcInputs = net.tran[56].inputArc;
parcOutputs = net.tran[56].outputArc;
InitArc( &parcInputs[0], 1, 90, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 99, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 162, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 88, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 57, "", 4, 0, 0, 4, 3, NULL, TE_1_9, NULL );
net.tran[57].number[1] = 0;
net.tran[57].number[2] = 18;
net.tran[57].number[3] = 9;
parcInputs = net.tran[57].inputArc;
parcOutputs = net.tran[57].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 132, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 87, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 86, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 58, "", 4, 0, 0, 4, 3, NULL, TE_1_10, NULL );
net.tran[58].number[1] = 0;
net.tran[58].number[2] = 18;
net.tran[58].number[3] = 10;
parcInputs = net.tran[58].inputArc;
parcOutputs = net.tran[58].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 132, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 160, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 90, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 59, "", 4, 0, 0, 4, 3, NULL, TE_1_11, NULL );
net.tran[59].number[1] = 0;
net.tran[59].number[2] = 18;
net.tran[59].number[3] = 11;
parcInputs = net.tran[59].inputArc;
parcOutputs = net.tran[59].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 163, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 132, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 87, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 168, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 60, "", 4, 2, 2, 3, 4, TF_1_12, NULL, NULL );
net.tran[60].number[1] = 0;
net.tran[60].number[2] = 18;
net.tran[60].number[3] = 12;
parcInputs = net.tran[60].inputArc;
parcOutputs = net.tran[60].outputArc;
InitArc( &parcInputs[0], 1, 168, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 162, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 91, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 61, "", 4, 0, 0, 4, 3, NULL, TE_1_13, NULL );
net.tran[61].number[1] = 0;
net.tran[61].number[2] = 18;
net.tran[61].number[3] = 13;
parcInputs = net.tran[61].inputArc;
parcOutputs = net.tran[61].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 163, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 132, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 160, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 169, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 62, "", 4, 2, 2, 3, 4, TF_1_14, NULL, NULL );
net.tran[62].number[1] = 0;
net.tran[62].number[2] = 18;
net.tran[62].number[3] = 14;
parcInputs = net.tran[62].inputArc;
parcOutputs = net.tran[62].outputArc;
InitArc( &parcInputs[0], 1, 169, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 162, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 88, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 63, "", 4, 2, 2, 3, 4, TF_1_15, NULL, NULL );
net.tran[63].number[1] = 0;
net.tran[63].number[2] = 18;
net.tran[63].number[3] = 15;
parcInputs = net.tran[63].inputArc;
parcOutputs = net.tran[63].outputArc;
InitArc( &parcInputs[0], 1, 170, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 87, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 103, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 94, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 87, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 64, "", 4, 0, 0, 4, 3, NULL, TE_1_16, NULL );
net.tran[64].number[1] = 0;
net.tran[64].number[2] = 18;
net.tran[64].number[3] = 16;
parcInputs = net.tran[64].inputArc;
parcOutputs = net.tran[64].outputArc;
InitArc( &parcInputs[0], 1, 162, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 166, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 151, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 170, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 89, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 65, "", 4, 2, 2, 3, 4, TF_1_17, NULL, NULL );
net.tran[65].number[1] = 0;
net.tran[65].number[2] = 18;
net.tran[65].number[3] = 17;
parcInputs = net.tran[65].inputArc;
parcOutputs = net.tran[65].outputArc;
InitArc( &parcInputs[0], 1, 171, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 87, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 103, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 92, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 87, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 66, "", 4, 0, 0, 4, 3, NULL, TE_1_18, NULL );
net.tran[66].number[1] = 0;
net.tran[66].number[2] = 18;
net.tran[66].number[3] = 18;
parcInputs = net.tran[66].inputArc;
parcOutputs = net.tran[66].outputArc;
InitArc( &parcInputs[0], 1, 166, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 151, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 171, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 89, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 67, "", 4, 2, 2, 3, 4, TF_1_19, NULL, NULL );
net.tran[67].number[1] = 0;
net.tran[67].number[2] = 18;
net.tran[67].number[3] = 19;
parcInputs = net.tran[67].inputArc;
parcOutputs = net.tran[67].outputArc;
InitArc( &parcInputs[0], 1, 172, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 87, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 101, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 94, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 87, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 68, "", 4, 0, 0, 4, 3, NULL, TE_1_20, NULL );
net.tran[68].number[1] = 0;
net.tran[68].number[2] = 18;
net.tran[68].number[3] = 20;
parcInputs = net.tran[68].inputArc;
parcOutputs = net.tran[68].outputArc;
InitArc( &parcInputs[0], 1, 165, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 151, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 172, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 89, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 69, "", 4, 2, 2, 3, 4, TF_1_21, NULL, NULL );
net.tran[69].number[1] = 0;
net.tran[69].number[2] = 18;
net.tran[69].number[3] = 21;
parcInputs = net.tran[69].inputArc;
parcOutputs = net.tran[69].outputArc;
InitArc( &parcInputs[0], 1, 173, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 87, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 101, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 92, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 87, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 70, "", 4, 0, 0, 4, 3, NULL, TE_1_22, NULL );
net.tran[70].number[1] = 0;
net.tran[70].number[2] = 18;
net.tran[70].number[3] = 22;
parcInputs = net.tran[70].inputArc;
parcOutputs = net.tran[70].outputArc;
InitArc( &parcInputs[0], 1, 165, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 151, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 173, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 89, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 71, "", 4, 2, 2, 3, 3, TF_1_23, NULL, NULL );
net.tran[71].number[1] = 0;
net.tran[71].number[2] = 18;
net.tran[71].number[3] = 23;
parcInputs = net.tran[71].inputArc;
parcOutputs = net.tran[71].outputArc;
InitArc( &parcInputs[0], 1, 174, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 121, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 87, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 121, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 87, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 88, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 72, "", 4, 2, 2, 3, 3, TF_1_24, NULL, NULL );
net.tran[72].number[1] = 0;
net.tran[72].number[2] = 18;
net.tran[72].number[3] = 24;
parcInputs = net.tran[72].inputArc;
parcOutputs = net.tran[72].outputArc;
InitArc( &parcInputs[0], 1, 175, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 149, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 164, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 149, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 73, "", 4, 0, 0, 3, 3, NULL, TE_1_25, NULL );
net.tran[73].number[1] = 0;
net.tran[73].number[2] = 18;
net.tran[73].number[3] = 25;
parcInputs = net.tran[73].inputArc;
parcOutputs = net.tran[73].outputArc;
InitArc( &parcInputs[0], 1, 121, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 151, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 160, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 174, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 121, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 89, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 74, "", 4, 0, 0, 3, 3, NULL, TE_1_26, NULL );
net.tran[74].number[1] = 0;
net.tran[74].number[2] = 18;
net.tran[74].number[3] = 26;
parcInputs = net.tran[74].inputArc;
parcOutputs = net.tran[74].outputArc;
InitArc( &parcInputs[0], 1, 123, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 163, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 149, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 175, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 149, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 75, "", 4, 0, 0, 4, 3, NULL, TE_1_27, NULL );
net.tran[75].number[1] = 0;
net.tran[75].number[2] = 18;
net.tran[75].number[3] = 27;
parcInputs = net.tran[75].inputArc;
parcOutputs = net.tran[75].outputArc;
InitArc( &parcInputs[0], 1, 160, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 163, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 151, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 176, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 89, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 76, "", 4, 2, 2, 3, 4, TF_1_28, NULL, NULL );
net.tran[76].number[1] = 0;
net.tran[76].number[2] = 18;
net.tran[76].number[3] = 28;
parcInputs = net.tran[76].inputArc;
parcOutputs = net.tran[76].outputArc;
InitArc( &parcInputs[0], 1, 176, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 87, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 164, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 87, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 88, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 77, "", 4, 2, 2, 3, 3, TF_1_29, NULL, NULL );
net.tran[77].number[1] = 0;
net.tran[77].number[2] = 18;
net.tran[77].number[3] = 29;
parcInputs = net.tran[77].inputArc;
parcOutputs = net.tran[77].outputArc;
InitArc( &parcInputs[0], 1, 177, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 110, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 110, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 94, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 161, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 78, "", 4, 0, 0, 3, 3, NULL, TE_1_30, NULL );
net.tran[78].number[1] = 0;
net.tran[78].number[2] = 18;
net.tran[78].number[3] = 30;
parcInputs = net.tran[78].inputArc;
parcOutputs = net.tran[78].outputArc;
InitArc( &parcInputs[0], 1, 110, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 162, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 142, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 177, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 110, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 93, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 79, "", 4, 0, 0, 4, 3, NULL, TE_1_31, NULL );
net.tran[79].number[1] = 0;
net.tran[79].number[2] = 18;
net.tran[79].number[3] = 31;
parcInputs = net.tran[79].inputArc;
parcOutputs = net.tran[79].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 165, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 142, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 178, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 93, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 80, "", 4, 2, 2, 3, 4, TF_1_32, NULL, NULL );
net.tran[80].number[1] = 0;
net.tran[80].number[2] = 18;
net.tran[80].number[3] = 32;
parcInputs = net.tran[80].inputArc;
parcOutputs = net.tran[80].outputArc;
InitArc( &parcInputs[0], 1, 178, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 101, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 94, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 161, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 81, "", 4, 2, 2, 3, 3, TF_1_33, NULL, NULL );
net.tran[81].number[1] = 0;
net.tran[81].number[2] = 18;
net.tran[81].number[3] = 33;
parcInputs = net.tran[81].inputArc;
parcOutputs = net.tran[81].outputArc;
InitArc( &parcInputs[0], 1, 179, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 144, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 101, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 144, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 82, "", 4, 0, 0, 3, 3, NULL, TE_1_34, NULL );
net.tran[82].number[1] = 0;
net.tran[82].number[2] = 18;
net.tran[82].number[3] = 34;
parcInputs = net.tran[82].inputArc;
parcOutputs = net.tran[82].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 165, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 144, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 179, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 144, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 83, "", 4, 0, 0, 4, 3, NULL, TE_1_35, NULL );
net.tran[83].number[1] = 0;
net.tran[83].number[2] = 18;
net.tran[83].number[3] = 35;
parcInputs = net.tran[83].inputArc;
parcOutputs = net.tran[83].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 142, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 87, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 180, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 93, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 84, "", 4, 2, 2, 3, 4, TF_1_36, NULL, NULL );
net.tran[84].number[1] = 0;
net.tran[84].number[2] = 18;
net.tran[84].number[3] = 36;
parcInputs = net.tran[84].inputArc;
parcOutputs = net.tran[84].outputArc;
InitArc( &parcInputs[0], 1, 180, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 99, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 161, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 91, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 85, "", 4, 2, 2, 3, 4, TF_1_37, NULL, NULL );
net.tran[85].number[1] = 0;
net.tran[85].number[2] = 18;
net.tran[85].number[3] = 37;
parcInputs = net.tran[85].inputArc;
parcOutputs = net.tran[85].outputArc;
InitArc( &parcInputs[0], 1, 181, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 99, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 161, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 88, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 86, "", 4, 0, 0, 4, 3, NULL, TE_1_38, NULL );
net.tran[86].number[1] = 0;
net.tran[86].number[2] = 18;
net.tran[86].number[3] = 38;
parcInputs = net.tran[86].inputArc;
parcOutputs = net.tran[86].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 142, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 160, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 181, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 93, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 87, "", 4, 2, 2, 3, 4, TF_1_39, NULL, NULL );
net.tran[87].number[1] = 0;
net.tran[87].number[2] = 18;
net.tran[87].number[3] = 39;
parcInputs = net.tran[87].inputArc;
parcOutputs = net.tran[87].outputArc;
InitArc( &parcInputs[0], 1, 182, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 161, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 91, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 88, "", 4, 0, 0, 4, 3, NULL, TE_1_40, NULL );
net.tran[88].number[1] = 0;
net.tran[88].number[2] = 18;
net.tran[88].number[3] = 40;
parcInputs = net.tran[88].inputArc;
parcOutputs = net.tran[88].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 163, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 142, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 87, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 182, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 93, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 89, "", 4, 2, 2, 3, 4, TF_1_41, NULL, NULL );
net.tran[89].number[1] = 0;
net.tran[89].number[2] = 18;
net.tran[89].number[3] = 41;
parcInputs = net.tran[89].inputArc;
parcOutputs = net.tran[89].outputArc;
InitArc( &parcInputs[0], 1, 183, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 166, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 166, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 161, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 88, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 90, "", 4, 0, 0, 4, 3, NULL, TE_1_42, NULL );
net.tran[90].number[1] = 0;
net.tran[90].number[2] = 18;
net.tran[90].number[3] = 42;
parcInputs = net.tran[90].inputArc;
parcOutputs = net.tran[90].outputArc;
InitArc( &parcInputs[0], 1, 106, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 163, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 142, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 160, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 183, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 102, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 93, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 91, "", 4, 0, 0, 4, 3, NULL, TE_1_43, NULL );
net.tran[91].number[1] = 0;
net.tran[91].number[2] = 18;
net.tran[91].number[3] = 43;
parcInputs = net.tran[91].inputArc;
parcOutputs = net.tran[91].outputArc;
InitArc( &parcInputs[0], 1, 166, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 159, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 184, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 154, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 92, "", 4, 2, 2, 3, 4, TF_1_44, NULL, NULL );
net.tran[92].number[1] = 0;
net.tran[92].number[2] = 18;
net.tran[92].number[3] = 44;
parcInputs = net.tran[92].inputArc;
parcOutputs = net.tran[92].outputArc;
InitArc( &parcInputs[0], 1, 184, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 160, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 103, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 94, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 160, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 93, "", 4, 2, 2, 3, 4, TF_1_45, NULL, NULL );
net.tran[93].number[1] = 0;
net.tran[93].number[2] = 18;
net.tran[93].number[3] = 45;
parcInputs = net.tran[93].inputArc;
parcOutputs = net.tran[93].outputArc;
InitArc( &parcInputs[0], 1, 185, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 160, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 103, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 92, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 160, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 94, "", 4, 0, 0, 4, 3, NULL, TE_1_46, NULL );
net.tran[94].number[1] = 0;
net.tran[94].number[2] = 18;
net.tran[94].number[3] = 46;
parcInputs = net.tran[94].inputArc;
parcOutputs = net.tran[94].outputArc;
InitArc( &parcInputs[0], 1, 166, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 159, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 185, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 154, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 95, "", 4, 2, 2, 3, 4, TF_1_47, NULL, NULL );
net.tran[95].number[1] = 0;
net.tran[95].number[2] = 18;
net.tran[95].number[3] = 47;
parcInputs = net.tran[95].inputArc;
parcOutputs = net.tran[95].outputArc;
InitArc( &parcInputs[0], 1, 186, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 160, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 101, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 94, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 160, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 96, "", 4, 0, 0, 4, 3, NULL, TE_1_48, NULL );
net.tran[96].number[1] = 0;
net.tran[96].number[2] = 18;
net.tran[96].number[3] = 48;
parcInputs = net.tran[96].inputArc;
parcOutputs = net.tran[96].outputArc;
InitArc( &parcInputs[0], 1, 165, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 159, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 186, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 154, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 97, "", 4, 2, 2, 3, 4, TF_1_49, NULL, NULL );
net.tran[97].number[1] = 0;
net.tran[97].number[2] = 18;
net.tran[97].number[3] = 49;
parcInputs = net.tran[97].inputArc;
parcOutputs = net.tran[97].outputArc;
InitArc( &parcInputs[0], 1, 187, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 160, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 101, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 164, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 92, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 160, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 98, "", 4, 0, 0, 4, 3, NULL, TE_1_50, NULL );
net.tran[98].number[1] = 0;
net.tran[98].number[2] = 18;
net.tran[98].number[3] = 50;
parcInputs = net.tran[98].inputArc;
parcOutputs = net.tran[98].outputArc;
InitArc( &parcInputs[0], 1, 165, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 123, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 159, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 187, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 154, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 99, "", 4, 2, 2, 3, 3, TF_1_51, NULL, NULL );
net.tran[99].number[1] = 0;
net.tran[99].number[2] = 18;
net.tran[99].number[3] = 51;
parcInputs = net.tran[99].inputArc;
parcOutputs = net.tran[99].outputArc;
InitArc( &parcInputs[0], 1, 188, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 121, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 160, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 121, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 91, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 160, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 100, "", 4, 0, 0, 3, 3, NULL, TE_1_52, NULL );
net.tran[100].number[1] = 0;
net.tran[100].number[2] = 18;
net.tran[100].number[3] = 52;
parcInputs = net.tran[100].inputArc;
parcOutputs = net.tran[100].outputArc;
InitArc( &parcInputs[0], 1, 121, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 87, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 159, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 188, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 121, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 154, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 101, "", 4, 2, 2, 3, 4, TF_1_53, NULL, NULL );
net.tran[101].number[1] = 0;
net.tran[101].number[2] = 18;
net.tran[101].number[3] = 53;
parcInputs = net.tran[101].inputArc;
parcOutputs = net.tran[101].outputArc;
InitArc( &parcInputs[0], 1, 189, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 160, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 164, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 91, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 160, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 102, "", 4, 0, 0, 4, 3, NULL, TE_1_54, NULL );
net.tran[102].number[1] = 0;
net.tran[102].number[2] = 18;
net.tran[102].number[3] = 54;
parcInputs = net.tran[102].inputArc;
parcOutputs = net.tran[102].outputArc;
InitArc( &parcInputs[0], 1, 123, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 163, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 87, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 159, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 189, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 154, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 103, "", 4, 2, 2, 3, 3, TF_1_55, NULL, NULL );
net.tran[103].number[1] = 0;
net.tran[103].number[2] = 18;
net.tran[103].number[3] = 55;
parcInputs = net.tran[103].inputArc;
parcOutputs = net.tran[103].outputArc;
InitArc( &parcInputs[0], 1, 190, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 155, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 164, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 97, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 155, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 104, "", 4, 0, 0, 3, 3, NULL, TE_1_56, NULL );
net.tran[104].number[1] = 0;
net.tran[104].number[2] = 18;
net.tran[104].number[3] = 56;
parcInputs = net.tran[104].inputArc;
parcOutputs = net.tran[104].outputArc;
InitArc( &parcInputs[0], 1, 123, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 163, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 155, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 190, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 98, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 155, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 105, "", 4, 0, 0, 3, 3, NULL, TE_1_57, NULL );
net.tran[105].number[1] = 0;
net.tran[105].number[2] = 18;
net.tran[105].number[3] = 57;
parcInputs = net.tran[105].inputArc;
parcOutputs = net.tran[105].outputArc;
InitArc( &parcInputs[0], 1, 166, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 112, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 135, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 191, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 100, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 135, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 106, "", 4, 2, 2, 3, 3, TF_1_58, NULL, NULL );
net.tran[106].number[1] = 0;
net.tran[106].number[2] = 18;
net.tran[106].number[3] = 58;
parcInputs = net.tran[106].inputArc;
parcOutputs = net.tran[106].outputArc;
InitArc( &parcInputs[0], 1, 191, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 165, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 135, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 103, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 165, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 135, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 107, "", 4, 0, 0, 4, 3, NULL, TE_1_59, NULL );
net.tran[107].number[1] = 0;
net.tran[107].number[2] = 18;
net.tran[107].number[3] = 59;
parcInputs = net.tran[107].inputArc;
parcOutputs = net.tran[107].outputArc;
InitArc( &parcInputs[0], 1, 166, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 112, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 132, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 161, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 192, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 100, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 108, "", 4, 2, 2, 3, 4, TF_1_60, NULL, NULL );
net.tran[108].number[1] = 0;
net.tran[108].number[2] = 18;
net.tran[108].number[3] = 60;
parcInputs = net.tran[108].inputArc;
parcOutputs = net.tran[108].outputArc;
InitArc( &parcInputs[0], 1, 192, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 165, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 103, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 165, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 162, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 92, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 109, "", 4, 0, 0, 3, 3, NULL, TE_1_61, NULL );
net.tran[109].number[1] = 0;
net.tran[109].number[2] = 18;
net.tran[109].number[3] = 61;
parcInputs = net.tran[109].inputArc;
parcOutputs = net.tran[109].outputArc;
InitArc( &parcInputs[0], 1, 117, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 132, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 161, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 193, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 117, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 110, "", 4, 2, 2, 3, 3, TF_1_62, NULL, NULL );
net.tran[110].number[1] = 0;
net.tran[110].number[2] = 18;
net.tran[110].number[3] = 62;
parcInputs = net.tran[110].inputArc;
parcOutputs = net.tran[110].outputArc;
InitArc( &parcInputs[0], 1, 193, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 162, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 117, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 117, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 162, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 92, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 111, "", 4, 0, 0, 4, 3, NULL, TE_1_63, NULL );
net.tran[111].number[1] = 0;
net.tran[111].number[2] = 18;
net.tran[111].number[3] = 63;
parcInputs = net.tran[111].inputArc;
parcOutputs = net.tran[111].outputArc;
InitArc( &parcInputs[0], 1, 112, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 132, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 87, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 194, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 100, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 112, "", 4, 2, 2, 3, 4, TF_1_64, NULL, NULL );
net.tran[112].number[1] = 0;
net.tran[112].number[2] = 18;
net.tran[112].number[3] = 64;
parcInputs = net.tran[112].inputArc;
parcOutputs = net.tran[112].outputArc;
InitArc( &parcInputs[0], 1, 194, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 165, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 162, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 165, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 99, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 162, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 91, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 113, "", 4, 0, 0, 4, 3, NULL, TE_1_65, NULL );
net.tran[113].number[1] = 0;
net.tran[113].number[2] = 18;
net.tran[113].number[3] = 65;
parcInputs = net.tran[113].inputArc;
parcOutputs = net.tran[113].outputArc;
InitArc( &parcInputs[0], 1, 112, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 164, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 132, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 160, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 195, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 100, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 95, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;


DefineNet6();
}
#endif /* SEGMENTED_MEMORY */
#endif /* CONST_NET */

