/* this file was generated from the NETMAN file:
	define12.c
	07/09/98 15:09:14
*/
#define SUPER_USER
#include "petri.h"
#include "userfunc.h"
#include <stdlib.h>

#ifndef CONST_NET
#ifdef SEGMENTED_MEMORY
void DefineNet12()
{
NCTArc *parcInputs, *parcOutputs;

InitTransition( 587, "", 3, 1, 0, 1, 1, NULL, NULL, TT_3_269 );
net.tran[587].number[1] = 1;
net.tran[587].number[2] = 269;
parcInputs = net.tran[587].inputArc;
parcOutputs = net.tran[587].outputArc;
InitArc( &parcInputs[0], 1, 524, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 513, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 588, "", 3, 2, 0, 1, 1, NULL, NULL, TT_3_270 );
net.tran[588].number[1] = 1;
net.tran[588].number[2] = 270;
parcInputs = net.tran[588].inputArc;
parcOutputs = net.tran[588].outputArc;
InitArc( &parcInputs[0], 1, 525, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 524, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 589, "", 3, 2, 0, 1, 1, NULL, NULL, TT_3_271 );
net.tran[589].number[1] = 1;
net.tran[589].number[2] = 271;
parcInputs = net.tran[589].inputArc;
parcOutputs = net.tran[589].outputArc;
InitArc( &parcInputs[0], 1, 528, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 527, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 590, "", 3, 0, 0, 2, 3, TF_3_272, TE_3_272, NULL );
net.tran[590].number[1] = 1;
net.tran[590].number[2] = 272;
parcInputs = net.tran[590].inputArc;
parcOutputs = net.tran[590].outputArc;
InitArc( &parcInputs[0], 1, 271, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 532, 0, 0 );
InitArc( &parcOutputs[0], 1, 273, 0, 0 );
InitArc( &parcOutputs[1], 1, 328, 0, 0 );
InitArc( &parcOutputs[2], 1, 525, 0, 3 );
parcOutputs[2].color[0].var = &vehicle ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
parcOutputs[2].color[1].var = &intersection ;
parcOutputs[2].color[1].flags = 0 ;
parcOutputs[2].color[1].size = 1 ;
parcOutputs[2].color[2].var = &bay ;
parcOutputs[2].color[2].flags = 0 ;
parcOutputs[2].color[2].size = 1 ;

InitTransition( 591, "", 3, 0, 0, 2, 3, TF_3_273, TE_3_273, NULL );
net.tran[591].number[1] = 1;
net.tran[591].number[2] = 273;
parcInputs = net.tran[591].inputArc;
parcOutputs = net.tran[591].outputArc;
InitArc( &parcInputs[0], 1, 322, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 533, 0, 0 );
InitArc( &parcOutputs[0], 1, 320, 0, 0 );
InitArc( &parcOutputs[1], 1, 324, 0, 0 );
InitArc( &parcOutputs[2], 1, 528, 0, 3 );
parcOutputs[2].color[0].var = &vehicle ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
parcOutputs[2].color[1].var = &intersection ;
parcOutputs[2].color[1].flags = 0 ;
parcOutputs[2].color[1].size = 1 ;
parcOutputs[2].color[2].var = &bay ;
parcOutputs[2].color[2].flags = 0 ;
parcOutputs[2].color[2].size = 1 ;

InitTransition( 592, "", 3, 0, 0, 2, 2, TF_3_275, NULL, NULL );
net.tran[592].number[1] = 1;
net.tran[592].number[2] = 275;
parcInputs = net.tran[592].inputArc;
parcOutputs = net.tran[592].outputArc;
InitArc( &parcInputs[0], 1, 328, 0, 0 );
InitArc( &parcInputs[1], 1, 529, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = (TOKEN_VALUE*)6 ;
parcInputs[1].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 270, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 526, 0, 0 );

InitTransition( 593, "", 3, 0, 0, 2, 2, TF_3_276, NULL, NULL );
net.tran[593].number[1] = 1;
net.tran[593].number[2] = 276;
parcInputs = net.tran[593].inputArc;
parcOutputs = net.tran[593].outputArc;
InitArc( &parcInputs[0], 1, 320, 0, 0 );
InitArc( &parcInputs[1], 1, 529, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = (TOKEN_VALUE*)3 ;
parcInputs[1].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 321, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 526, 0, 0 );

InitTransition( 594, "", 3, 0, 0, 2, 1, TF_3_277, NULL, NULL );
net.tran[594].number[1] = 1;
net.tran[594].number[2] = 277;
parcInputs = net.tran[594].inputArc;
parcOutputs = net.tran[594].outputArc;
InitArc( &parcInputs[0], 1, 268, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 526, 0, 0 );
InitArc( &parcOutputs[0], 1, 529, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 595, "", 3, 0, 0, 2, 2, TF_3_287, NULL, NULL );
net.tran[595].number[1] = 1;
net.tran[595].number[2] = 287;
parcInputs = net.tran[595].inputArc;
parcOutputs = net.tran[595].outputArc;
InitArc( &parcInputs[0], 1, 503, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 531, 0, 0 );
InitArc( &parcOutputs[0], 1, 530, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 533, 0, 0 );

InitTransition( 596, "", 3, 0, 0, 2, 2, TF_3_288, NULL, NULL );
net.tran[596].number[1] = 1;
net.tran[596].number[2] = 288;
parcInputs = net.tran[596].inputArc;
parcOutputs = net.tran[596].outputArc;
InitArc( &parcInputs[0], 1, 500, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)7 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 531, 0, 0 );
InitArc( &parcOutputs[0], 1, 530, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 532, 0, 0 );

InitTransition( 597, "", 3, 0, 0, 2, 2, TF_3_289, NULL, NULL );
net.tran[597].number[1] = 1;
net.tran[597].number[2] = 289;
parcInputs = net.tran[597].inputArc;
parcOutputs = net.tran[597].outputArc;
InitArc( &parcInputs[0], 1, 514, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)7 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 531, 0, 0 );
InitArc( &parcOutputs[0], 1, 530, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 533, 0, 0 );

InitTransition( 598, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[598].number[1] = 2;
net.tran[598].number[2] = 3;
net.tran[598].number[3] = 1;
parcInputs = net.tran[598].inputArc;
parcOutputs = net.tran[598].outputArc;
InitArc( &parcInputs[0], 1, 542, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 541, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 599, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[599].number[1] = 2;
net.tran[599].number[2] = 3;
net.tran[599].number[3] = 2;
parcInputs = net.tran[599].inputArc;
parcOutputs = net.tran[599].outputArc;
InitArc( &parcInputs[0], 1, 539, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 538, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 600, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[600].number[1] = 2;
net.tran[600].number[2] = 3;
net.tran[600].number[3] = 3;
parcInputs = net.tran[600].inputArc;
parcOutputs = net.tran[600].outputArc;
InitArc( &parcInputs[0], 1, 540, 0, 0 );
InitArc( &parcInputs[1], 1, 541, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 539, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 601, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[601].number[1] = 2;
net.tran[601].number[2] = 3;
net.tran[601].number[3] = 4;
parcInputs = net.tran[601].inputArc;
parcOutputs = net.tran[601].outputArc;
InitArc( &parcInputs[0], 1, 539, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 543, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 602, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[602].number[1] = 2;
net.tran[602].number[2] = 3;
net.tran[602].number[3] = 5;
parcInputs = net.tran[602].inputArc;
parcOutputs = net.tran[602].outputArc;
InitArc( &parcInputs[0], 1, 537, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 542, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 603, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[603].number[1] = 2;
net.tran[603].number[2] = 3;
net.tran[603].number[3] = 6;
parcInputs = net.tran[603].inputArc;
parcOutputs = net.tran[603].outputArc;
InitArc( &parcInputs[0], 1, 543, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 538, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 604, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[604].number[1] = 2;
net.tran[604].number[2] = 8;
net.tran[604].number[3] = 1;
parcInputs = net.tran[604].inputArc;
parcOutputs = net.tran[604].outputArc;
InitArc( &parcInputs[0], 1, 550, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 549, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 605, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[605].number[1] = 2;
net.tran[605].number[2] = 8;
net.tran[605].number[3] = 2;
parcInputs = net.tran[605].inputArc;
parcOutputs = net.tran[605].outputArc;
InitArc( &parcInputs[0], 1, 547, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 546, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 606, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[606].number[1] = 2;
net.tran[606].number[2] = 8;
net.tran[606].number[3] = 3;
parcInputs = net.tran[606].inputArc;
parcOutputs = net.tran[606].outputArc;
InitArc( &parcInputs[0], 1, 548, 0, 0 );
InitArc( &parcInputs[1], 1, 549, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 547, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 607, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[607].number[1] = 2;
net.tran[607].number[2] = 8;
net.tran[607].number[3] = 4;
parcInputs = net.tran[607].inputArc;
parcOutputs = net.tran[607].outputArc;
InitArc( &parcInputs[0], 1, 547, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 551, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 608, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[608].number[1] = 2;
net.tran[608].number[2] = 8;
net.tran[608].number[3] = 5;
parcInputs = net.tran[608].inputArc;
parcOutputs = net.tran[608].outputArc;
InitArc( &parcInputs[0], 1, 545, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 550, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 609, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[609].number[1] = 2;
net.tran[609].number[2] = 8;
net.tran[609].number[3] = 6;
parcInputs = net.tran[609].inputArc;
parcOutputs = net.tran[609].outputArc;
InitArc( &parcInputs[0], 1, 551, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 546, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 610, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[610].number[1] = 2;
net.tran[610].number[2] = 10;
net.tran[610].number[3] = 1;
parcInputs = net.tran[610].inputArc;
parcOutputs = net.tran[610].outputArc;
InitArc( &parcInputs[0], 1, 557, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 556, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 611, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[611].number[1] = 2;
net.tran[611].number[2] = 10;
net.tran[611].number[3] = 2;
parcInputs = net.tran[611].inputArc;
parcOutputs = net.tran[611].outputArc;
InitArc( &parcInputs[0], 1, 554, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 553, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 612, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[612].number[1] = 2;
net.tran[612].number[2] = 10;
net.tran[612].number[3] = 3;
parcInputs = net.tran[612].inputArc;
parcOutputs = net.tran[612].outputArc;
InitArc( &parcInputs[0], 1, 555, 0, 0 );
InitArc( &parcInputs[1], 1, 556, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 554, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 613, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[613].number[1] = 2;
net.tran[613].number[2] = 10;
net.tran[613].number[3] = 4;
parcInputs = net.tran[613].inputArc;
parcOutputs = net.tran[613].outputArc;
InitArc( &parcInputs[0], 1, 554, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 558, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 614, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[614].number[1] = 2;
net.tran[614].number[2] = 10;
net.tran[614].number[3] = 5;
parcInputs = net.tran[614].inputArc;
parcOutputs = net.tran[614].outputArc;
InitArc( &parcInputs[0], 1, 552, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 557, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 615, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[615].number[1] = 2;
net.tran[615].number[2] = 10;
net.tran[615].number[3] = 6;
parcInputs = net.tran[615].inputArc;
parcOutputs = net.tran[615].outputArc;
InitArc( &parcInputs[0], 1, 558, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 553, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 616, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[616].number[1] = 2;
net.tran[616].number[2] = 11;
net.tran[616].number[3] = 1;
parcInputs = net.tran[616].inputArc;
parcOutputs = net.tran[616].outputArc;
InitArc( &parcInputs[0], 1, 564, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 563, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 617, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[617].number[1] = 2;
net.tran[617].number[2] = 11;
net.tran[617].number[3] = 2;
parcInputs = net.tran[617].inputArc;
parcOutputs = net.tran[617].outputArc;
InitArc( &parcInputs[0], 1, 561, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 560, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 618, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[618].number[1] = 2;
net.tran[618].number[2] = 11;
net.tran[618].number[3] = 3;
parcInputs = net.tran[618].inputArc;
parcOutputs = net.tran[618].outputArc;
InitArc( &parcInputs[0], 1, 562, 0, 0 );
InitArc( &parcInputs[1], 1, 563, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 561, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 619, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[619].number[1] = 2;
net.tran[619].number[2] = 11;
net.tran[619].number[3] = 4;
parcInputs = net.tran[619].inputArc;
parcOutputs = net.tran[619].outputArc;
InitArc( &parcInputs[0], 1, 561, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 565, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 620, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[620].number[1] = 2;
net.tran[620].number[2] = 11;
net.tran[620].number[3] = 5;
parcInputs = net.tran[620].inputArc;
parcOutputs = net.tran[620].outputArc;
InitArc( &parcInputs[0], 1, 559, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 564, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 621, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[621].number[1] = 2;
net.tran[621].number[2] = 11;
net.tran[621].number[3] = 6;
parcInputs = net.tran[621].inputArc;
parcOutputs = net.tran[621].outputArc;
InitArc( &parcInputs[0], 1, 565, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 560, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 622, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[622].number[1] = 2;
net.tran[622].number[2] = 12;
net.tran[622].number[3] = 1;
parcInputs = net.tran[622].inputArc;
parcOutputs = net.tran[622].outputArc;
InitArc( &parcInputs[0], 1, 571, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 570, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 623, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[623].number[1] = 2;
net.tran[623].number[2] = 12;
net.tran[623].number[3] = 2;
parcInputs = net.tran[623].inputArc;
parcOutputs = net.tran[623].outputArc;
InitArc( &parcInputs[0], 1, 568, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 567, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 624, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[624].number[1] = 2;
net.tran[624].number[2] = 12;
net.tran[624].number[3] = 3;
parcInputs = net.tran[624].inputArc;
parcOutputs = net.tran[624].outputArc;
InitArc( &parcInputs[0], 1, 569, 0, 0 );
InitArc( &parcInputs[1], 1, 570, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 568, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 625, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[625].number[1] = 2;
net.tran[625].number[2] = 12;
net.tran[625].number[3] = 4;
parcInputs = net.tran[625].inputArc;
parcOutputs = net.tran[625].outputArc;
InitArc( &parcInputs[0], 1, 568, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 572, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 626, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[626].number[1] = 2;
net.tran[626].number[2] = 12;
net.tran[626].number[3] = 5;
parcInputs = net.tran[626].inputArc;
parcOutputs = net.tran[626].outputArc;
InitArc( &parcInputs[0], 1, 566, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 571, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 627, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[627].number[1] = 2;
net.tran[627].number[2] = 12;
net.tran[627].number[3] = 6;
parcInputs = net.tran[627].inputArc;
parcOutputs = net.tran[627].outputArc;
InitArc( &parcInputs[0], 1, 572, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 567, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 628, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[628].number[1] = 2;
net.tran[628].number[2] = 13;
net.tran[628].number[3] = 1;
parcInputs = net.tran[628].inputArc;
parcOutputs = net.tran[628].outputArc;
InitArc( &parcInputs[0], 1, 578, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 577, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 629, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[629].number[1] = 2;
net.tran[629].number[2] = 13;
net.tran[629].number[3] = 2;
parcInputs = net.tran[629].inputArc;
parcOutputs = net.tran[629].outputArc;
InitArc( &parcInputs[0], 1, 575, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 574, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 630, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[630].number[1] = 2;
net.tran[630].number[2] = 13;
net.tran[630].number[3] = 3;
parcInputs = net.tran[630].inputArc;
parcOutputs = net.tran[630].outputArc;
InitArc( &parcInputs[0], 1, 576, 0, 0 );
InitArc( &parcInputs[1], 1, 577, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 575, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 631, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[631].number[1] = 2;
net.tran[631].number[2] = 13;
net.tran[631].number[3] = 4;
parcInputs = net.tran[631].inputArc;
parcOutputs = net.tran[631].outputArc;
InitArc( &parcInputs[0], 1, 575, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 579, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 632, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[632].number[1] = 2;
net.tran[632].number[2] = 13;
net.tran[632].number[3] = 5;
parcInputs = net.tran[632].inputArc;
parcOutputs = net.tran[632].outputArc;
InitArc( &parcInputs[0], 1, 573, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 578, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 633, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[633].number[1] = 2;
net.tran[633].number[2] = 13;
net.tran[633].number[3] = 6;
parcInputs = net.tran[633].inputArc;
parcOutputs = net.tran[633].outputArc;
InitArc( &parcInputs[0], 1, 579, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 574, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 634, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[634].number[1] = 2;
net.tran[634].number[2] = 14;
net.tran[634].number[3] = 1;
parcInputs = net.tran[634].inputArc;
parcOutputs = net.tran[634].outputArc;
InitArc( &parcInputs[0], 1, 585, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 584, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 635, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[635].number[1] = 2;
net.tran[635].number[2] = 14;
net.tran[635].number[3] = 2;
parcInputs = net.tran[635].inputArc;
parcOutputs = net.tran[635].outputArc;
InitArc( &parcInputs[0], 1, 582, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 581, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 636, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[636].number[1] = 2;
net.tran[636].number[2] = 14;
net.tran[636].number[3] = 3;
parcInputs = net.tran[636].inputArc;
parcOutputs = net.tran[636].outputArc;
InitArc( &parcInputs[0], 1, 583, 0, 0 );
InitArc( &parcInputs[1], 1, 584, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 582, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 637, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[637].number[1] = 2;
net.tran[637].number[2] = 14;
net.tran[637].number[3] = 4;
parcInputs = net.tran[637].inputArc;
parcOutputs = net.tran[637].outputArc;
InitArc( &parcInputs[0], 1, 582, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 586, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 638, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[638].number[1] = 2;
net.tran[638].number[2] = 14;
net.tran[638].number[3] = 5;
parcInputs = net.tran[638].inputArc;
parcOutputs = net.tran[638].outputArc;
InitArc( &parcInputs[0], 1, 580, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 585, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 639, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[639].number[1] = 2;
net.tran[639].number[2] = 14;
net.tran[639].number[3] = 6;
parcInputs = net.tran[639].inputArc;
parcOutputs = net.tran[639].outputArc;
InitArc( &parcInputs[0], 1, 586, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 581, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 640, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[640].number[1] = 2;
net.tran[640].number[2] = 16;
net.tran[640].number[3] = 1;
parcInputs = net.tran[640].inputArc;
parcOutputs = net.tran[640].outputArc;
InitArc( &parcInputs[0], 1, 593, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 592, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 641, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[641].number[1] = 2;
net.tran[641].number[2] = 16;
net.tran[641].number[3] = 2;
parcInputs = net.tran[641].inputArc;
parcOutputs = net.tran[641].outputArc;
InitArc( &parcInputs[0], 1, 590, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 589, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 642, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[642].number[1] = 2;
net.tran[642].number[2] = 16;
net.tran[642].number[3] = 3;
parcInputs = net.tran[642].inputArc;
parcOutputs = net.tran[642].outputArc;
InitArc( &parcInputs[0], 1, 591, 0, 0 );
InitArc( &parcInputs[1], 1, 592, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 590, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 643, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[643].number[1] = 2;
net.tran[643].number[2] = 16;
net.tran[643].number[3] = 4;
parcInputs = net.tran[643].inputArc;
parcOutputs = net.tran[643].outputArc;
InitArc( &parcInputs[0], 1, 590, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 594, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 644, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[644].number[1] = 2;
net.tran[644].number[2] = 16;
net.tran[644].number[3] = 5;
parcInputs = net.tran[644].inputArc;
parcOutputs = net.tran[644].outputArc;
InitArc( &parcInputs[0], 1, 588, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 593, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 645, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[645].number[1] = 2;
net.tran[645].number[2] = 16;
net.tran[645].number[3] = 6;
parcInputs = net.tran[645].inputArc;
parcOutputs = net.tran[645].outputArc;
InitArc( &parcInputs[0], 1, 594, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 589, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 646, "", 4, 0, 0, 2, 1, TF_1_0, NULL, NULL );
net.tran[646].number[1] = 2;
net.tran[646].number[2] = 18;
net.tran[646].number[3] = 0;
parcInputs = net.tran[646].inputArc;
parcOutputs = net.tran[646].outputArc;
InitArc( &parcInputs[0], 1, 688, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 689, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 596, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;

InitTransition( 647, "", 4, 2, 2, 3, 3, TF_1_1, NULL, NULL );
net.tran[647].number[1] = 2;
net.tran[647].number[2] = 18;
net.tran[647].number[3] = 1;
parcInputs = net.tran[647].inputArc;
parcOutputs = net.tran[647].outputArc;
InitArc( &parcInputs[0], 1, 606, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 644, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 696, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 644, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 696, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 626, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 648, "", 4, 2, 2, 3, 3, TF_1_2, NULL, NULL );
net.tran[648].number[1] = 2;
net.tran[648].number[2] = 18;
net.tran[648].number[3] = 2;
parcInputs = net.tran[648].inputArc;
parcOutputs = net.tran[648].outputArc;
InitArc( &parcInputs[0], 1, 618, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 669, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 700, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 700, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 635, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 669, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 649, "", 4, 2, 2, 3, 4, TF_1_3, NULL, NULL );
net.tran[649].number[1] = 2;
net.tran[649].number[2] = 18;
net.tran[649].number[3] = 3;
parcInputs = net.tran[649].inputArc;
parcOutputs = net.tran[649].outputArc;
InitArc( &parcInputs[0], 1, 619, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 700, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 696, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 700, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 635, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 696, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 626, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 650, "", 4, 0, 0, 3, 3, NULL, TE_1_4, NULL );
net.tran[650].number[1] = 2;
net.tran[650].number[2] = 18;
net.tran[650].number[3] = 4;
parcInputs = net.tran[650].inputArc;
parcOutputs = net.tran[650].outputArc;
InitArc( &parcInputs[0], 1, 695, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 666, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 644, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 606, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 644, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 629, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 651, "", 4, 0, 0, 3, 3, NULL, TE_1_5, NULL );
net.tran[651].number[1] = 2;
net.tran[651].number[2] = 18;
net.tran[651].number[3] = 5;
parcInputs = net.tran[651].inputArc;
parcOutputs = net.tran[651].outputArc;
InitArc( &parcInputs[0], 1, 640, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 699, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 669, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 618, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 669, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 636, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 652, "", 4, 0, 0, 4, 3, NULL, TE_1_6, NULL );
net.tran[652].number[1] = 2;
net.tran[652].number[2] = 18;
net.tran[652].number[3] = 6;
parcInputs = net.tran[652].inputArc;
parcOutputs = net.tran[652].outputArc;
InitArc( &parcInputs[0], 1, 640, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 699, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 666, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 695, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 619, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 636, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 629, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 653, "", 4, 2, 2, 3, 4, TF_1_7, NULL, NULL );
net.tran[653].number[1] = 2;
net.tran[653].number[2] = 18;
net.tran[653].number[3] = 7;
parcInputs = net.tran[653].inputArc;
parcOutputs = net.tran[653].outputArc;
InitArc( &parcInputs[0], 1, 620, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 700, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 696, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 700, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 633, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 696, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 625, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 654, "", 4, 2, 2, 3, 4, TF_1_8, NULL, NULL );
net.tran[654].number[1] = 2;
net.tran[654].number[2] = 18;
net.tran[654].number[3] = 8;
parcInputs = net.tran[654].inputArc;
parcOutputs = net.tran[654].outputArc;
InitArc( &parcInputs[0], 1, 624, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 700, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 696, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 700, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 633, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 696, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 622, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 655, "", 4, 0, 0, 4, 3, NULL, TE_1_9, NULL );
net.tran[655].number[1] = 2;
net.tran[655].number[2] = 18;
net.tran[655].number[3] = 9;
parcInputs = net.tran[655].inputArc;
parcOutputs = net.tran[655].outputArc;
InitArc( &parcInputs[0], 1, 640, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 698, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 666, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 621, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 620, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 636, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 629, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 656, "", 4, 0, 0, 4, 3, NULL, TE_1_10, NULL );
net.tran[656].number[1] = 2;
net.tran[656].number[2] = 18;
net.tran[656].number[3] = 10;
parcInputs = net.tran[656].inputArc;
parcOutputs = net.tran[656].outputArc;
InitArc( &parcInputs[0], 1, 640, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 698, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 666, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 694, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 624, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 636, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 629, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 657, "", 4, 0, 0, 4, 3, NULL, TE_1_11, NULL );
net.tran[657].number[1] = 2;
net.tran[657].number[2] = 18;
net.tran[657].number[3] = 11;
parcInputs = net.tran[657].inputArc;
parcOutputs = net.tran[657].outputArc;
InitArc( &parcInputs[0], 1, 640, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 697, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 666, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 621, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 702, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 636, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 629, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 658, "", 4, 2, 2, 3, 4, TF_1_12, NULL, NULL );
net.tran[658].number[1] = 2;
net.tran[658].number[2] = 18;
net.tran[658].number[3] = 12;
parcInputs = net.tran[658].inputArc;
parcOutputs = net.tran[658].outputArc;
InitArc( &parcInputs[0], 1, 702, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 700, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 696, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 700, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 631, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 696, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 625, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;


DefineNet13();
}
#endif /* SEGMENTED_MEMORY */
#endif /* CONST_NET */

