/* this file was generated from the NETMAN file:
	define08.c
	07/09/98 15:09:13
*/
#define SUPER_USER
#include "petri.h"
#include "userfunc.h"
#include <stdlib.h>

#ifndef CONST_NET
#ifdef SEGMENTED_MEMORY
void DefineNet8()
{
NCTArc *parcInputs, *parcOutputs;

InitTransition( 284, "", 3, 0, 0, 2, 1, TF_3_261, NULL, NULL );
net.tran[284].number[1] = 0;
net.tran[284].number[2] = 261;
parcInputs = net.tran[284].inputArc;
parcOutputs = net.tran[284].outputArc;
InitArc( &parcInputs[0], 1, 0, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 252, 0, 0 );
InitArc( &parcOutputs[0], 1, 254, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 285, "", 3, 0, 0, 2, 2, TF_3_265, NULL, NULL );
net.tran[285].number[1] = 0;
net.tran[285].number[2] = 265;
parcInputs = net.tran[285].inputArc;
parcOutputs = net.tran[285].outputArc;
InitArc( &parcInputs[0], 1, 235, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)1 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 256, 0, 0 );
InitArc( &parcOutputs[0], 1, 255, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 265, 0, 0 );

InitTransition( 286, "", 3, 0, 0, 2, 2, TF_3_266, NULL, NULL );
net.tran[286].number[1] = 0;
net.tran[286].number[2] = 266;
parcInputs = net.tran[286].inputArc;
parcOutputs = net.tran[286].outputArc;
InitArc( &parcInputs[0], 1, 233, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)1 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 256, 0, 0 );
InitArc( &parcOutputs[0], 1, 255, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 265, 0, 0 );

InitTransition( 287, "", 3, 1, 0, 1, 1, TF_3_268, NULL, TT_3_268 );
net.tran[287].number[1] = 0;
net.tran[287].number[2] = 268;
parcInputs = net.tran[287].inputArc;
parcOutputs = net.tran[287].outputArc;
InitArc( &parcInputs[0], 1, 260, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 243, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 288, "", 3, 1, 0, 1, 1, NULL, NULL, TT_3_269 );
net.tran[288].number[1] = 0;
net.tran[288].number[2] = 269;
parcInputs = net.tran[288].inputArc;
parcOutputs = net.tran[288].outputArc;
InitArc( &parcInputs[0], 1, 257, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 246, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 289, "", 3, 2, 0, 1, 1, NULL, NULL, TT_3_270 );
net.tran[289].number[1] = 0;
net.tran[289].number[2] = 270;
parcInputs = net.tran[289].inputArc;
parcOutputs = net.tran[289].outputArc;
InitArc( &parcInputs[0], 1, 258, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 257, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 290, "", 3, 2, 0, 1, 1, NULL, NULL, TT_3_271 );
net.tran[290].number[1] = 0;
net.tran[290].number[2] = 271;
parcInputs = net.tran[290].inputArc;
parcOutputs = net.tran[290].outputArc;
InitArc( &parcInputs[0], 1, 261, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 260, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 291, "", 3, 0, 0, 2, 3, TF_3_272, TE_3_272, NULL );
net.tran[291].number[1] = 0;
net.tran[291].number[2] = 272;
parcInputs = net.tran[291].inputArc;
parcOutputs = net.tran[291].outputArc;
InitArc( &parcInputs[0], 1, 4, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 265, 0, 0 );
InitArc( &parcOutputs[0], 1, 6, 0, 0 );
InitArc( &parcOutputs[1], 1, 61, 0, 0 );
InitArc( &parcOutputs[2], 1, 258, 0, 3 );
parcOutputs[2].color[0].var = &vehicle ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
parcOutputs[2].color[1].var = &intersection ;
parcOutputs[2].color[1].flags = 0 ;
parcOutputs[2].color[1].size = 1 ;
parcOutputs[2].color[2].var = &bay ;
parcOutputs[2].color[2].flags = 0 ;
parcOutputs[2].color[2].size = 1 ;

InitTransition( 292, "", 3, 0, 0, 2, 3, TF_3_273, TE_3_273, NULL );
net.tran[292].number[1] = 0;
net.tran[292].number[2] = 273;
parcInputs = net.tran[292].inputArc;
parcOutputs = net.tran[292].outputArc;
InitArc( &parcInputs[0], 1, 55, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 266, 0, 0 );
InitArc( &parcOutputs[0], 1, 53, 0, 0 );
InitArc( &parcOutputs[1], 1, 57, 0, 0 );
InitArc( &parcOutputs[2], 1, 261, 0, 3 );
parcOutputs[2].color[0].var = &vehicle ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
parcOutputs[2].color[1].var = &intersection ;
parcOutputs[2].color[1].flags = 0 ;
parcOutputs[2].color[1].size = 1 ;
parcOutputs[2].color[2].var = &bay ;
parcOutputs[2].color[2].flags = 0 ;
parcOutputs[2].color[2].size = 1 ;

InitTransition( 293, "", 3, 0, 0, 2, 2, TF_3_275, NULL, NULL );
net.tran[293].number[1] = 0;
net.tran[293].number[2] = 275;
parcInputs = net.tran[293].inputArc;
parcOutputs = net.tran[293].outputArc;
InitArc( &parcInputs[0], 1, 61, 0, 0 );
InitArc( &parcInputs[1], 1, 262, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = (TOKEN_VALUE*)6 ;
parcInputs[1].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 3, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 259, 0, 0 );

InitTransition( 294, "", 3, 0, 0, 2, 2, TF_3_276, NULL, NULL );
net.tran[294].number[1] = 0;
net.tran[294].number[2] = 276;
parcInputs = net.tran[294].inputArc;
parcOutputs = net.tran[294].outputArc;
InitArc( &parcInputs[0], 1, 53, 0, 0 );
InitArc( &parcInputs[1], 1, 262, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = (TOKEN_VALUE*)3 ;
parcInputs[1].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 54, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 259, 0, 0 );

InitTransition( 295, "", 3, 0, 0, 2, 1, TF_3_277, NULL, NULL );
net.tran[295].number[1] = 0;
net.tran[295].number[2] = 277;
parcInputs = net.tran[295].inputArc;
parcOutputs = net.tran[295].outputArc;
InitArc( &parcInputs[0], 1, 1, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 259, 0, 0 );
InitArc( &parcOutputs[0], 1, 262, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 296, "", 3, 0, 0, 2, 2, TF_3_287, NULL, NULL );
net.tran[296].number[1] = 0;
net.tran[296].number[2] = 287;
parcInputs = net.tran[296].inputArc;
parcOutputs = net.tran[296].outputArc;
InitArc( &parcInputs[0], 1, 236, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 264, 0, 0 );
InitArc( &parcOutputs[0], 1, 263, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 266, 0, 0 );

InitTransition( 297, "", 3, 0, 0, 2, 2, TF_3_288, NULL, NULL );
net.tran[297].number[1] = 0;
net.tran[297].number[2] = 288;
parcInputs = net.tran[297].inputArc;
parcOutputs = net.tran[297].outputArc;
InitArc( &parcInputs[0], 1, 233, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)7 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 264, 0, 0 );
InitArc( &parcOutputs[0], 1, 263, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 265, 0, 0 );

InitTransition( 298, "", 3, 0, 0, 2, 2, TF_3_289, NULL, NULL );
net.tran[298].number[1] = 0;
net.tran[298].number[2] = 289;
parcInputs = net.tran[298].inputArc;
parcOutputs = net.tran[298].outputArc;
InitArc( &parcInputs[0], 1, 247, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)7 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 264, 0, 0 );
InitArc( &parcOutputs[0], 1, 263, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 266, 0, 0 );

InitTransition( 299, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[299].number[1] = 1;
net.tran[299].number[2] = 3;
net.tran[299].number[3] = 1;
parcInputs = net.tran[299].inputArc;
parcOutputs = net.tran[299].outputArc;
InitArc( &parcInputs[0], 1, 275, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 274, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 300, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[300].number[1] = 1;
net.tran[300].number[2] = 3;
net.tran[300].number[3] = 2;
parcInputs = net.tran[300].inputArc;
parcOutputs = net.tran[300].outputArc;
InitArc( &parcInputs[0], 1, 272, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 271, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 301, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[301].number[1] = 1;
net.tran[301].number[2] = 3;
net.tran[301].number[3] = 3;
parcInputs = net.tran[301].inputArc;
parcOutputs = net.tran[301].outputArc;
InitArc( &parcInputs[0], 1, 273, 0, 0 );
InitArc( &parcInputs[1], 1, 274, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 272, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 302, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[302].number[1] = 1;
net.tran[302].number[2] = 3;
net.tran[302].number[3] = 4;
parcInputs = net.tran[302].inputArc;
parcOutputs = net.tran[302].outputArc;
InitArc( &parcInputs[0], 1, 272, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 276, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 303, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[303].number[1] = 1;
net.tran[303].number[2] = 3;
net.tran[303].number[3] = 5;
parcInputs = net.tran[303].inputArc;
parcOutputs = net.tran[303].outputArc;
InitArc( &parcInputs[0], 1, 270, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 275, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 304, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[304].number[1] = 1;
net.tran[304].number[2] = 3;
net.tran[304].number[3] = 6;
parcInputs = net.tran[304].inputArc;
parcOutputs = net.tran[304].outputArc;
InitArc( &parcInputs[0], 1, 276, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 271, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 305, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[305].number[1] = 1;
net.tran[305].number[2] = 8;
net.tran[305].number[3] = 1;
parcInputs = net.tran[305].inputArc;
parcOutputs = net.tran[305].outputArc;
InitArc( &parcInputs[0], 1, 283, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 282, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 306, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[306].number[1] = 1;
net.tran[306].number[2] = 8;
net.tran[306].number[3] = 2;
parcInputs = net.tran[306].inputArc;
parcOutputs = net.tran[306].outputArc;
InitArc( &parcInputs[0], 1, 280, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 279, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 307, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[307].number[1] = 1;
net.tran[307].number[2] = 8;
net.tran[307].number[3] = 3;
parcInputs = net.tran[307].inputArc;
parcOutputs = net.tran[307].outputArc;
InitArc( &parcInputs[0], 1, 281, 0, 0 );
InitArc( &parcInputs[1], 1, 282, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 280, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 308, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[308].number[1] = 1;
net.tran[308].number[2] = 8;
net.tran[308].number[3] = 4;
parcInputs = net.tran[308].inputArc;
parcOutputs = net.tran[308].outputArc;
InitArc( &parcInputs[0], 1, 280, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 284, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 309, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[309].number[1] = 1;
net.tran[309].number[2] = 8;
net.tran[309].number[3] = 5;
parcInputs = net.tran[309].inputArc;
parcOutputs = net.tran[309].outputArc;
InitArc( &parcInputs[0], 1, 278, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 283, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 310, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[310].number[1] = 1;
net.tran[310].number[2] = 8;
net.tran[310].number[3] = 6;
parcInputs = net.tran[310].inputArc;
parcOutputs = net.tran[310].outputArc;
InitArc( &parcInputs[0], 1, 284, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 279, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 311, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[311].number[1] = 1;
net.tran[311].number[2] = 10;
net.tran[311].number[3] = 1;
parcInputs = net.tran[311].inputArc;
parcOutputs = net.tran[311].outputArc;
InitArc( &parcInputs[0], 1, 290, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 289, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 312, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[312].number[1] = 1;
net.tran[312].number[2] = 10;
net.tran[312].number[3] = 2;
parcInputs = net.tran[312].inputArc;
parcOutputs = net.tran[312].outputArc;
InitArc( &parcInputs[0], 1, 287, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 286, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 313, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[313].number[1] = 1;
net.tran[313].number[2] = 10;
net.tran[313].number[3] = 3;
parcInputs = net.tran[313].inputArc;
parcOutputs = net.tran[313].outputArc;
InitArc( &parcInputs[0], 1, 288, 0, 0 );
InitArc( &parcInputs[1], 1, 289, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 287, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 314, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[314].number[1] = 1;
net.tran[314].number[2] = 10;
net.tran[314].number[3] = 4;
parcInputs = net.tran[314].inputArc;
parcOutputs = net.tran[314].outputArc;
InitArc( &parcInputs[0], 1, 287, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 291, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 315, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[315].number[1] = 1;
net.tran[315].number[2] = 10;
net.tran[315].number[3] = 5;
parcInputs = net.tran[315].inputArc;
parcOutputs = net.tran[315].outputArc;
InitArc( &parcInputs[0], 1, 285, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 290, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 316, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[316].number[1] = 1;
net.tran[316].number[2] = 10;
net.tran[316].number[3] = 6;
parcInputs = net.tran[316].inputArc;
parcOutputs = net.tran[316].outputArc;
InitArc( &parcInputs[0], 1, 291, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 286, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 317, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[317].number[1] = 1;
net.tran[317].number[2] = 11;
net.tran[317].number[3] = 1;
parcInputs = net.tran[317].inputArc;
parcOutputs = net.tran[317].outputArc;
InitArc( &parcInputs[0], 1, 297, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 296, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 318, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[318].number[1] = 1;
net.tran[318].number[2] = 11;
net.tran[318].number[3] = 2;
parcInputs = net.tran[318].inputArc;
parcOutputs = net.tran[318].outputArc;
InitArc( &parcInputs[0], 1, 294, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 293, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 319, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[319].number[1] = 1;
net.tran[319].number[2] = 11;
net.tran[319].number[3] = 3;
parcInputs = net.tran[319].inputArc;
parcOutputs = net.tran[319].outputArc;
InitArc( &parcInputs[0], 1, 295, 0, 0 );
InitArc( &parcInputs[1], 1, 296, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 294, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 320, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[320].number[1] = 1;
net.tran[320].number[2] = 11;
net.tran[320].number[3] = 4;
parcInputs = net.tran[320].inputArc;
parcOutputs = net.tran[320].outputArc;
InitArc( &parcInputs[0], 1, 294, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 298, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 321, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[321].number[1] = 1;
net.tran[321].number[2] = 11;
net.tran[321].number[3] = 5;
parcInputs = net.tran[321].inputArc;
parcOutputs = net.tran[321].outputArc;
InitArc( &parcInputs[0], 1, 292, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 297, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 322, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[322].number[1] = 1;
net.tran[322].number[2] = 11;
net.tran[322].number[3] = 6;
parcInputs = net.tran[322].inputArc;
parcOutputs = net.tran[322].outputArc;
InitArc( &parcInputs[0], 1, 298, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 293, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 323, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[323].number[1] = 1;
net.tran[323].number[2] = 12;
net.tran[323].number[3] = 1;
parcInputs = net.tran[323].inputArc;
parcOutputs = net.tran[323].outputArc;
InitArc( &parcInputs[0], 1, 304, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 303, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 324, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[324].number[1] = 1;
net.tran[324].number[2] = 12;
net.tran[324].number[3] = 2;
parcInputs = net.tran[324].inputArc;
parcOutputs = net.tran[324].outputArc;
InitArc( &parcInputs[0], 1, 301, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 300, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 325, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[325].number[1] = 1;
net.tran[325].number[2] = 12;
net.tran[325].number[3] = 3;
parcInputs = net.tran[325].inputArc;
parcOutputs = net.tran[325].outputArc;
InitArc( &parcInputs[0], 1, 302, 0, 0 );
InitArc( &parcInputs[1], 1, 303, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 301, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 326, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[326].number[1] = 1;
net.tran[326].number[2] = 12;
net.tran[326].number[3] = 4;
parcInputs = net.tran[326].inputArc;
parcOutputs = net.tran[326].outputArc;
InitArc( &parcInputs[0], 1, 301, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 305, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 327, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[327].number[1] = 1;
net.tran[327].number[2] = 12;
net.tran[327].number[3] = 5;
parcInputs = net.tran[327].inputArc;
parcOutputs = net.tran[327].outputArc;
InitArc( &parcInputs[0], 1, 299, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 304, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 328, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[328].number[1] = 1;
net.tran[328].number[2] = 12;
net.tran[328].number[3] = 6;
parcInputs = net.tran[328].inputArc;
parcOutputs = net.tran[328].outputArc;
InitArc( &parcInputs[0], 1, 305, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 300, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 329, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[329].number[1] = 1;
net.tran[329].number[2] = 13;
net.tran[329].number[3] = 1;
parcInputs = net.tran[329].inputArc;
parcOutputs = net.tran[329].outputArc;
InitArc( &parcInputs[0], 1, 311, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 310, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 330, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[330].number[1] = 1;
net.tran[330].number[2] = 13;
net.tran[330].number[3] = 2;
parcInputs = net.tran[330].inputArc;
parcOutputs = net.tran[330].outputArc;
InitArc( &parcInputs[0], 1, 308, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 307, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 331, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[331].number[1] = 1;
net.tran[331].number[2] = 13;
net.tran[331].number[3] = 3;
parcInputs = net.tran[331].inputArc;
parcOutputs = net.tran[331].outputArc;
InitArc( &parcInputs[0], 1, 309, 0, 0 );
InitArc( &parcInputs[1], 1, 310, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 308, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 332, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[332].number[1] = 1;
net.tran[332].number[2] = 13;
net.tran[332].number[3] = 4;
parcInputs = net.tran[332].inputArc;
parcOutputs = net.tran[332].outputArc;
InitArc( &parcInputs[0], 1, 308, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 312, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 333, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[333].number[1] = 1;
net.tran[333].number[2] = 13;
net.tran[333].number[3] = 5;
parcInputs = net.tran[333].inputArc;
parcOutputs = net.tran[333].outputArc;
InitArc( &parcInputs[0], 1, 306, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 311, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 334, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[334].number[1] = 1;
net.tran[334].number[2] = 13;
net.tran[334].number[3] = 6;
parcInputs = net.tran[334].inputArc;
parcOutputs = net.tran[334].outputArc;
InitArc( &parcInputs[0], 1, 312, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 307, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 335, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[335].number[1] = 1;
net.tran[335].number[2] = 14;
net.tran[335].number[3] = 1;
parcInputs = net.tran[335].inputArc;
parcOutputs = net.tran[335].outputArc;
InitArc( &parcInputs[0], 1, 318, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 317, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 336, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[336].number[1] = 1;
net.tran[336].number[2] = 14;
net.tran[336].number[3] = 2;
parcInputs = net.tran[336].inputArc;
parcOutputs = net.tran[336].outputArc;
InitArc( &parcInputs[0], 1, 315, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 314, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 337, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[337].number[1] = 1;
net.tran[337].number[2] = 14;
net.tran[337].number[3] = 3;
parcInputs = net.tran[337].inputArc;
parcOutputs = net.tran[337].outputArc;
InitArc( &parcInputs[0], 1, 316, 0, 0 );
InitArc( &parcInputs[1], 1, 317, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 315, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 338, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[338].number[1] = 1;
net.tran[338].number[2] = 14;
net.tran[338].number[3] = 4;
parcInputs = net.tran[338].inputArc;
parcOutputs = net.tran[338].outputArc;
InitArc( &parcInputs[0], 1, 315, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 319, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 339, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[339].number[1] = 1;
net.tran[339].number[2] = 14;
net.tran[339].number[3] = 5;
parcInputs = net.tran[339].inputArc;
parcOutputs = net.tran[339].outputArc;
InitArc( &parcInputs[0], 1, 313, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 318, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 340, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[340].number[1] = 1;
net.tran[340].number[2] = 14;
net.tran[340].number[3] = 6;
parcInputs = net.tran[340].inputArc;
parcOutputs = net.tran[340].outputArc;
InitArc( &parcInputs[0], 1, 319, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 314, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 341, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[341].number[1] = 1;
net.tran[341].number[2] = 16;
net.tran[341].number[3] = 1;
parcInputs = net.tran[341].inputArc;
parcOutputs = net.tran[341].outputArc;
InitArc( &parcInputs[0], 1, 326, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 325, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 342, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[342].number[1] = 1;
net.tran[342].number[2] = 16;
net.tran[342].number[3] = 2;
parcInputs = net.tran[342].inputArc;
parcOutputs = net.tran[342].outputArc;
InitArc( &parcInputs[0], 1, 323, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 322, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 343, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[343].number[1] = 1;
net.tran[343].number[2] = 16;
net.tran[343].number[3] = 3;
parcInputs = net.tran[343].inputArc;
parcOutputs = net.tran[343].outputArc;
InitArc( &parcInputs[0], 1, 324, 0, 0 );
InitArc( &parcInputs[1], 1, 325, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 323, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 344, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[344].number[1] = 1;
net.tran[344].number[2] = 16;
net.tran[344].number[3] = 4;
parcInputs = net.tran[344].inputArc;
parcOutputs = net.tran[344].outputArc;
InitArc( &parcInputs[0], 1, 323, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 327, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 345, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[345].number[1] = 1;
net.tran[345].number[2] = 16;
net.tran[345].number[3] = 5;
parcInputs = net.tran[345].inputArc;
parcOutputs = net.tran[345].outputArc;
InitArc( &parcInputs[0], 1, 321, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 326, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 346, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[346].number[1] = 1;
net.tran[346].number[2] = 16;
net.tran[346].number[3] = 6;
parcInputs = net.tran[346].inputArc;
parcOutputs = net.tran[346].outputArc;
InitArc( &parcInputs[0], 1, 327, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 322, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 347, "", 4, 0, 0, 2, 1, TF_1_0, NULL, NULL );
net.tran[347].number[1] = 1;
net.tran[347].number[2] = 18;
net.tran[347].number[3] = 0;
parcInputs = net.tran[347].inputArc;
parcOutputs = net.tran[347].outputArc;
InitArc( &parcInputs[0], 1, 421, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 422, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 329, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;

InitTransition( 348, "", 4, 2, 2, 3, 3, TF_1_1, NULL, NULL );
net.tran[348].number[1] = 1;
net.tran[348].number[2] = 18;
net.tran[348].number[3] = 1;
parcInputs = net.tran[348].inputArc;
parcOutputs = net.tran[348].outputArc;
InitArc( &parcInputs[0], 1, 339, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 377, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 429, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 377, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 429, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 359, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 349, "", 4, 2, 2, 3, 3, TF_1_2, NULL, NULL );
net.tran[349].number[1] = 1;
net.tran[349].number[2] = 18;
net.tran[349].number[3] = 2;
parcInputs = net.tran[349].inputArc;
parcOutputs = net.tran[349].outputArc;
InitArc( &parcInputs[0], 1, 351, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 402, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 433, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 433, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 368, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 402, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 350, "", 4, 2, 2, 3, 4, TF_1_3, NULL, NULL );
net.tran[350].number[1] = 1;
net.tran[350].number[2] = 18;
net.tran[350].number[3] = 3;
parcInputs = net.tran[350].inputArc;
parcOutputs = net.tran[350].outputArc;
InitArc( &parcInputs[0], 1, 352, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 433, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 429, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 433, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 368, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 429, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 359, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 351, "", 4, 0, 0, 3, 3, NULL, TE_1_4, NULL );
net.tran[351].number[1] = 1;
net.tran[351].number[2] = 18;
net.tran[351].number[3] = 4;
parcInputs = net.tran[351].inputArc;
parcOutputs = net.tran[351].outputArc;
InitArc( &parcInputs[0], 1, 428, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 399, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 377, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 339, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 377, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 362, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 352, "", 4, 0, 0, 3, 3, NULL, TE_1_5, NULL );
net.tran[352].number[1] = 1;
net.tran[352].number[2] = 18;
net.tran[352].number[3] = 5;
parcInputs = net.tran[352].inputArc;
parcOutputs = net.tran[352].outputArc;
InitArc( &parcInputs[0], 1, 373, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 432, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 402, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 351, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 402, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 369, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 353, "", 4, 0, 0, 4, 3, NULL, TE_1_6, NULL );
net.tran[353].number[1] = 1;
net.tran[353].number[2] = 18;
net.tran[353].number[3] = 6;
parcInputs = net.tran[353].inputArc;
parcOutputs = net.tran[353].outputArc;
InitArc( &parcInputs[0], 1, 373, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 432, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 399, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 428, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 352, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 369, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 362, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 354, "", 4, 2, 2, 3, 4, TF_1_7, NULL, NULL );
net.tran[354].number[1] = 1;
net.tran[354].number[2] = 18;
net.tran[354].number[3] = 7;
parcInputs = net.tran[354].inputArc;
parcOutputs = net.tran[354].outputArc;
InitArc( &parcInputs[0], 1, 353, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 433, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 429, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 433, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 366, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 429, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 358, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 355, "", 4, 2, 2, 3, 4, TF_1_8, NULL, NULL );
net.tran[355].number[1] = 1;
net.tran[355].number[2] = 18;
net.tran[355].number[3] = 8;
parcInputs = net.tran[355].inputArc;
parcOutputs = net.tran[355].outputArc;
InitArc( &parcInputs[0], 1, 357, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 433, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 429, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 433, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 366, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 429, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 355, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 356, "", 4, 0, 0, 4, 3, NULL, TE_1_9, NULL );
net.tran[356].number[1] = 1;
net.tran[356].number[2] = 18;
net.tran[356].number[3] = 9;
parcInputs = net.tran[356].inputArc;
parcOutputs = net.tran[356].outputArc;
InitArc( &parcInputs[0], 1, 373, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 431, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 399, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 354, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 353, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 369, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 362, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;


DefineNet9();
}
#endif /* SEGMENTED_MEMORY */
#endif /* CONST_NET */

