/* this file was generated from the NETMAN file:
	define16.c
	07/09/98 15:09:15
*/
#define SUPER_USER
#include "petri.h"
#include "userfunc.h"
#include <stdlib.h>

#ifndef CONST_NET
#ifdef SEGMENTED_MEMORY
void DefineNet16()
{
NCTArc *parcInputs, *parcOutputs;

InitTransition( 890, "", 3, 0, 0, 2, 3, TF_3_273, TE_3_273, NULL );
net.tran[890].number[1] = 2;
net.tran[890].number[2] = 273;
parcInputs = net.tran[890].inputArc;
parcOutputs = net.tran[890].outputArc;
InitArc( &parcInputs[0], 1, 589, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 800, 0, 0 );
InitArc( &parcOutputs[0], 1, 587, 0, 0 );
InitArc( &parcOutputs[1], 1, 591, 0, 0 );
InitArc( &parcOutputs[2], 1, 795, 0, 3 );
parcOutputs[2].color[0].var = &vehicle ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
parcOutputs[2].color[1].var = &intersection ;
parcOutputs[2].color[1].flags = 0 ;
parcOutputs[2].color[1].size = 1 ;
parcOutputs[2].color[2].var = &bay ;
parcOutputs[2].color[2].flags = 0 ;
parcOutputs[2].color[2].size = 1 ;

InitTransition( 891, "", 3, 0, 0, 2, 2, TF_3_275, NULL, NULL );
net.tran[891].number[1] = 2;
net.tran[891].number[2] = 275;
parcInputs = net.tran[891].inputArc;
parcOutputs = net.tran[891].outputArc;
InitArc( &parcInputs[0], 1, 595, 0, 0 );
InitArc( &parcInputs[1], 1, 796, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = (TOKEN_VALUE*)6 ;
parcInputs[1].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 537, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 793, 0, 0 );

InitTransition( 892, "", 3, 0, 0, 2, 2, TF_3_276, NULL, NULL );
net.tran[892].number[1] = 2;
net.tran[892].number[2] = 276;
parcInputs = net.tran[892].inputArc;
parcOutputs = net.tran[892].outputArc;
InitArc( &parcInputs[0], 1, 587, 0, 0 );
InitArc( &parcInputs[1], 1, 796, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = (TOKEN_VALUE*)3 ;
parcInputs[1].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 588, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 793, 0, 0 );

InitTransition( 893, "", 3, 0, 0, 2, 1, TF_3_277, NULL, NULL );
net.tran[893].number[1] = 2;
net.tran[893].number[2] = 277;
parcInputs = net.tran[893].inputArc;
parcOutputs = net.tran[893].outputArc;
InitArc( &parcInputs[0], 1, 535, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 793, 0, 0 );
InitArc( &parcOutputs[0], 1, 796, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 894, "", 3, 0, 0, 2, 2, TF_3_287, NULL, NULL );
net.tran[894].number[1] = 2;
net.tran[894].number[2] = 287;
parcInputs = net.tran[894].inputArc;
parcOutputs = net.tran[894].outputArc;
InitArc( &parcInputs[0], 1, 770, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 798, 0, 0 );
InitArc( &parcOutputs[0], 1, 797, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 800, 0, 0 );

InitTransition( 895, "", 3, 0, 0, 2, 2, TF_3_288, NULL, NULL );
net.tran[895].number[1] = 2;
net.tran[895].number[2] = 288;
parcInputs = net.tran[895].inputArc;
parcOutputs = net.tran[895].outputArc;
InitArc( &parcInputs[0], 1, 767, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)7 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 798, 0, 0 );
InitArc( &parcOutputs[0], 1, 797, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 799, 0, 0 );

InitTransition( 896, "", 3, 0, 0, 2, 2, TF_3_289, NULL, NULL );
net.tran[896].number[1] = 2;
net.tran[896].number[2] = 289;
parcInputs = net.tran[896].inputArc;
parcOutputs = net.tran[896].outputArc;
InitArc( &parcInputs[0], 1, 781, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = (TOKEN_VALUE*)7 ;
parcInputs[0].color[2].flags = COMPARE_FLAG | VALUE_FLAG ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcInputs[1], 1, 798, 0, 0 );
InitArc( &parcOutputs[0], 1, 797, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[1], 1, 800, 0, 0 );

InitTransition( 897, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[897].number[1] = 3;
net.tran[897].number[2] = 3;
net.tran[897].number[3] = 1;
parcInputs = net.tran[897].inputArc;
parcOutputs = net.tran[897].outputArc;
InitArc( &parcInputs[0], 1, 809, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 808, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 898, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[898].number[1] = 3;
net.tran[898].number[2] = 3;
net.tran[898].number[3] = 2;
parcInputs = net.tran[898].inputArc;
parcOutputs = net.tran[898].outputArc;
InitArc( &parcInputs[0], 1, 806, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 805, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 899, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[899].number[1] = 3;
net.tran[899].number[2] = 3;
net.tran[899].number[3] = 3;
parcInputs = net.tran[899].inputArc;
parcOutputs = net.tran[899].outputArc;
InitArc( &parcInputs[0], 1, 807, 0, 0 );
InitArc( &parcInputs[1], 1, 808, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 806, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 900, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[900].number[1] = 3;
net.tran[900].number[2] = 3;
net.tran[900].number[3] = 4;
parcInputs = net.tran[900].inputArc;
parcOutputs = net.tran[900].outputArc;
InitArc( &parcInputs[0], 1, 806, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 810, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 901, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[901].number[1] = 3;
net.tran[901].number[2] = 3;
net.tran[901].number[3] = 5;
parcInputs = net.tran[901].inputArc;
parcOutputs = net.tran[901].outputArc;
InitArc( &parcInputs[0], 1, 804, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 809, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 902, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[902].number[1] = 3;
net.tran[902].number[2] = 3;
net.tran[902].number[3] = 6;
parcInputs = net.tran[902].inputArc;
parcOutputs = net.tran[902].outputArc;
InitArc( &parcInputs[0], 1, 810, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 805, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 903, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[903].number[1] = 3;
net.tran[903].number[2] = 8;
net.tran[903].number[3] = 1;
parcInputs = net.tran[903].inputArc;
parcOutputs = net.tran[903].outputArc;
InitArc( &parcInputs[0], 1, 817, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 816, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 904, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[904].number[1] = 3;
net.tran[904].number[2] = 8;
net.tran[904].number[3] = 2;
parcInputs = net.tran[904].inputArc;
parcOutputs = net.tran[904].outputArc;
InitArc( &parcInputs[0], 1, 814, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 813, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 905, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[905].number[1] = 3;
net.tran[905].number[2] = 8;
net.tran[905].number[3] = 3;
parcInputs = net.tran[905].inputArc;
parcOutputs = net.tran[905].outputArc;
InitArc( &parcInputs[0], 1, 815, 0, 0 );
InitArc( &parcInputs[1], 1, 816, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 814, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 906, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[906].number[1] = 3;
net.tran[906].number[2] = 8;
net.tran[906].number[3] = 4;
parcInputs = net.tran[906].inputArc;
parcOutputs = net.tran[906].outputArc;
InitArc( &parcInputs[0], 1, 814, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 818, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 907, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[907].number[1] = 3;
net.tran[907].number[2] = 8;
net.tran[907].number[3] = 5;
parcInputs = net.tran[907].inputArc;
parcOutputs = net.tran[907].outputArc;
InitArc( &parcInputs[0], 1, 812, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 817, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 908, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[908].number[1] = 3;
net.tran[908].number[2] = 8;
net.tran[908].number[3] = 6;
parcInputs = net.tran[908].inputArc;
parcOutputs = net.tran[908].outputArc;
InitArc( &parcInputs[0], 1, 818, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 813, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 909, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[909].number[1] = 3;
net.tran[909].number[2] = 10;
net.tran[909].number[3] = 1;
parcInputs = net.tran[909].inputArc;
parcOutputs = net.tran[909].outputArc;
InitArc( &parcInputs[0], 1, 824, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 823, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 910, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[910].number[1] = 3;
net.tran[910].number[2] = 10;
net.tran[910].number[3] = 2;
parcInputs = net.tran[910].inputArc;
parcOutputs = net.tran[910].outputArc;
InitArc( &parcInputs[0], 1, 821, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 820, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 911, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[911].number[1] = 3;
net.tran[911].number[2] = 10;
net.tran[911].number[3] = 3;
parcInputs = net.tran[911].inputArc;
parcOutputs = net.tran[911].outputArc;
InitArc( &parcInputs[0], 1, 822, 0, 0 );
InitArc( &parcInputs[1], 1, 823, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 821, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 912, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[912].number[1] = 3;
net.tran[912].number[2] = 10;
net.tran[912].number[3] = 4;
parcInputs = net.tran[912].inputArc;
parcOutputs = net.tran[912].outputArc;
InitArc( &parcInputs[0], 1, 821, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 825, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 913, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[913].number[1] = 3;
net.tran[913].number[2] = 10;
net.tran[913].number[3] = 5;
parcInputs = net.tran[913].inputArc;
parcOutputs = net.tran[913].outputArc;
InitArc( &parcInputs[0], 1, 819, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 824, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 914, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[914].number[1] = 3;
net.tran[914].number[2] = 10;
net.tran[914].number[3] = 6;
parcInputs = net.tran[914].inputArc;
parcOutputs = net.tran[914].outputArc;
InitArc( &parcInputs[0], 1, 825, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 820, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 915, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[915].number[1] = 3;
net.tran[915].number[2] = 11;
net.tran[915].number[3] = 1;
parcInputs = net.tran[915].inputArc;
parcOutputs = net.tran[915].outputArc;
InitArc( &parcInputs[0], 1, 831, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 830, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 916, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[916].number[1] = 3;
net.tran[916].number[2] = 11;
net.tran[916].number[3] = 2;
parcInputs = net.tran[916].inputArc;
parcOutputs = net.tran[916].outputArc;
InitArc( &parcInputs[0], 1, 828, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 827, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 917, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[917].number[1] = 3;
net.tran[917].number[2] = 11;
net.tran[917].number[3] = 3;
parcInputs = net.tran[917].inputArc;
parcOutputs = net.tran[917].outputArc;
InitArc( &parcInputs[0], 1, 829, 0, 0 );
InitArc( &parcInputs[1], 1, 830, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 828, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 918, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[918].number[1] = 3;
net.tran[918].number[2] = 11;
net.tran[918].number[3] = 4;
parcInputs = net.tran[918].inputArc;
parcOutputs = net.tran[918].outputArc;
InitArc( &parcInputs[0], 1, 828, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 832, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 919, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[919].number[1] = 3;
net.tran[919].number[2] = 11;
net.tran[919].number[3] = 5;
parcInputs = net.tran[919].inputArc;
parcOutputs = net.tran[919].outputArc;
InitArc( &parcInputs[0], 1, 826, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 831, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 920, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[920].number[1] = 3;
net.tran[920].number[2] = 11;
net.tran[920].number[3] = 6;
parcInputs = net.tran[920].inputArc;
parcOutputs = net.tran[920].outputArc;
InitArc( &parcInputs[0], 1, 832, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 827, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 921, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[921].number[1] = 3;
net.tran[921].number[2] = 12;
net.tran[921].number[3] = 1;
parcInputs = net.tran[921].inputArc;
parcOutputs = net.tran[921].outputArc;
InitArc( &parcInputs[0], 1, 838, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 837, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 922, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[922].number[1] = 3;
net.tran[922].number[2] = 12;
net.tran[922].number[3] = 2;
parcInputs = net.tran[922].inputArc;
parcOutputs = net.tran[922].outputArc;
InitArc( &parcInputs[0], 1, 835, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 834, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 923, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[923].number[1] = 3;
net.tran[923].number[2] = 12;
net.tran[923].number[3] = 3;
parcInputs = net.tran[923].inputArc;
parcOutputs = net.tran[923].outputArc;
InitArc( &parcInputs[0], 1, 836, 0, 0 );
InitArc( &parcInputs[1], 1, 837, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 835, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 924, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[924].number[1] = 3;
net.tran[924].number[2] = 12;
net.tran[924].number[3] = 4;
parcInputs = net.tran[924].inputArc;
parcOutputs = net.tran[924].outputArc;
InitArc( &parcInputs[0], 1, 835, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 839, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 925, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[925].number[1] = 3;
net.tran[925].number[2] = 12;
net.tran[925].number[3] = 5;
parcInputs = net.tran[925].inputArc;
parcOutputs = net.tran[925].outputArc;
InitArc( &parcInputs[0], 1, 833, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 838, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 926, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[926].number[1] = 3;
net.tran[926].number[2] = 12;
net.tran[926].number[3] = 6;
parcInputs = net.tran[926].inputArc;
parcOutputs = net.tran[926].outputArc;
InitArc( &parcInputs[0], 1, 839, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 834, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 927, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[927].number[1] = 3;
net.tran[927].number[2] = 13;
net.tran[927].number[3] = 1;
parcInputs = net.tran[927].inputArc;
parcOutputs = net.tran[927].outputArc;
InitArc( &parcInputs[0], 1, 845, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 844, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 928, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[928].number[1] = 3;
net.tran[928].number[2] = 13;
net.tran[928].number[3] = 2;
parcInputs = net.tran[928].inputArc;
parcOutputs = net.tran[928].outputArc;
InitArc( &parcInputs[0], 1, 842, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 841, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 929, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[929].number[1] = 3;
net.tran[929].number[2] = 13;
net.tran[929].number[3] = 3;
parcInputs = net.tran[929].inputArc;
parcOutputs = net.tran[929].outputArc;
InitArc( &parcInputs[0], 1, 843, 0, 0 );
InitArc( &parcInputs[1], 1, 844, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 842, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 930, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[930].number[1] = 3;
net.tran[930].number[2] = 13;
net.tran[930].number[3] = 4;
parcInputs = net.tran[930].inputArc;
parcOutputs = net.tran[930].outputArc;
InitArc( &parcInputs[0], 1, 842, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 846, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 931, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[931].number[1] = 3;
net.tran[931].number[2] = 13;
net.tran[931].number[3] = 5;
parcInputs = net.tran[931].inputArc;
parcOutputs = net.tran[931].outputArc;
InitArc( &parcInputs[0], 1, 840, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 845, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 932, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[932].number[1] = 3;
net.tran[932].number[2] = 13;
net.tran[932].number[3] = 6;
parcInputs = net.tran[932].inputArc;
parcOutputs = net.tran[932].outputArc;
InitArc( &parcInputs[0], 1, 846, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 841, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 933, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[933].number[1] = 3;
net.tran[933].number[2] = 14;
net.tran[933].number[3] = 1;
parcInputs = net.tran[933].inputArc;
parcOutputs = net.tran[933].outputArc;
InitArc( &parcInputs[0], 1, 852, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 851, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 934, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[934].number[1] = 3;
net.tran[934].number[2] = 14;
net.tran[934].number[3] = 2;
parcInputs = net.tran[934].inputArc;
parcOutputs = net.tran[934].outputArc;
InitArc( &parcInputs[0], 1, 849, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 848, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 935, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[935].number[1] = 3;
net.tran[935].number[2] = 14;
net.tran[935].number[3] = 3;
parcInputs = net.tran[935].inputArc;
parcOutputs = net.tran[935].outputArc;
InitArc( &parcInputs[0], 1, 850, 0, 0 );
InitArc( &parcInputs[1], 1, 851, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 849, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 936, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[936].number[1] = 3;
net.tran[936].number[2] = 14;
net.tran[936].number[3] = 4;
parcInputs = net.tran[936].inputArc;
parcOutputs = net.tran[936].outputArc;
InitArc( &parcInputs[0], 1, 849, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 853, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 937, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[937].number[1] = 3;
net.tran[937].number[2] = 14;
net.tran[937].number[3] = 5;
parcInputs = net.tran[937].inputArc;
parcOutputs = net.tran[937].outputArc;
InitArc( &parcInputs[0], 1, 847, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 852, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 938, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[938].number[1] = 3;
net.tran[938].number[2] = 14;
net.tran[938].number[3] = 6;
parcInputs = net.tran[938].inputArc;
parcOutputs = net.tran[938].outputArc;
InitArc( &parcInputs[0], 1, 853, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 848, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 939, "", 4, 2, 0.4, 1, 1, TF_2_1, NULL, NULL );
net.tran[939].number[1] = 3;
net.tran[939].number[2] = 16;
net.tran[939].number[3] = 1;
parcInputs = net.tran[939].inputArc;
parcOutputs = net.tran[939].outputArc;
InitArc( &parcInputs[0], 1, 860, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 859, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 940, "", 4, 0, 0, 1, 1, NULL, TE_2_2, NULL );
net.tran[940].number[1] = 3;
net.tran[940].number[2] = 16;
net.tran[940].number[3] = 2;
parcInputs = net.tran[940].inputArc;
parcOutputs = net.tran[940].outputArc;
InitArc( &parcInputs[0], 1, 857, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 856, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 941, "", 4, 2, 0.6, 2, 1, NULL, NULL, NULL );
net.tran[941].number[1] = 3;
net.tran[941].number[2] = 16;
net.tran[941].number[3] = 3;
parcInputs = net.tran[941].inputArc;
parcOutputs = net.tran[941].outputArc;
InitArc( &parcInputs[0], 1, 858, 0, 0 );
InitArc( &parcInputs[1], 1, 859, 0, 3 );
parcInputs[1].color[0].var = &vehicle ;
parcInputs[1].color[0].flags = 0 ;
parcInputs[1].color[0].size = 1 ;
parcInputs[1].color[1].var = &intersection ;
parcInputs[1].color[1].flags = 0 ;
parcInputs[1].color[1].size = 1 ;
parcInputs[1].color[2].var = &bay ;
parcInputs[1].color[2].flags = 0 ;
parcInputs[1].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 857, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 942, "", 4, 0, 0, 1, 1, NULL, TE_2_4, NULL );
net.tran[942].number[1] = 3;
net.tran[942].number[2] = 16;
net.tran[942].number[3] = 4;
parcInputs = net.tran[942].inputArc;
parcOutputs = net.tran[942].outputArc;
InitArc( &parcInputs[0], 1, 857, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 861, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 943, "", 4, 2, 1.3, 1, 1, NULL, NULL, NULL );
net.tran[943].number[1] = 3;
net.tran[943].number[2] = 16;
net.tran[943].number[3] = 5;
parcInputs = net.tran[943].inputArc;
parcOutputs = net.tran[943].outputArc;
InitArc( &parcInputs[0], 1, 855, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 860, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 944, "", 4, 2, 0, 1, 1, NULL, NULL, TT_2_6 );
net.tran[944].number[1] = 3;
net.tran[944].number[2] = 16;
net.tran[944].number[3] = 6;
parcInputs = net.tran[944].inputArc;
parcOutputs = net.tran[944].outputArc;
InitArc( &parcInputs[0], 1, 861, 0, 3 );
parcInputs[0].color[0].var = &vehicle ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
parcInputs[0].color[1].var = &intersection ;
parcInputs[0].color[1].flags = 0 ;
parcInputs[0].color[1].size = 1 ;
parcInputs[0].color[2].var = &bay ;
parcInputs[0].color[2].flags = 0 ;
parcInputs[0].color[2].size = 1 ;
InitArc( &parcOutputs[0], 1, 856, 0, 3 );
parcOutputs[0].color[0].var = &vehicle ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
parcOutputs[0].color[1].var = &intersection ;
parcOutputs[0].color[1].flags = 0 ;
parcOutputs[0].color[1].size = 1 ;
parcOutputs[0].color[2].var = &bay ;
parcOutputs[0].color[2].flags = 0 ;
parcOutputs[0].color[2].size = 1 ;

InitTransition( 945, "", 4, 0, 0, 2, 1, TF_1_0, NULL, NULL );
net.tran[945].number[1] = 3;
net.tran[945].number[2] = 18;
net.tran[945].number[3] = 0;
parcInputs = net.tran[945].inputArc;
parcOutputs = net.tran[945].outputArc;
InitArc( &parcInputs[0], 1, 955, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 956, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 863, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;

InitTransition( 946, "", 4, 2, 2, 3, 3, TF_1_1, NULL, NULL );
net.tran[946].number[1] = 3;
net.tran[946].number[2] = 18;
net.tran[946].number[3] = 1;
parcInputs = net.tran[946].inputArc;
parcOutputs = net.tran[946].outputArc;
InitArc( &parcInputs[0], 1, 873, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 911, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 963, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 911, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 963, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 893, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 947, "", 4, 2, 2, 3, 3, TF_1_2, NULL, NULL );
net.tran[947].number[1] = 3;
net.tran[947].number[2] = 18;
net.tran[947].number[3] = 2;
parcInputs = net.tran[947].inputArc;
parcOutputs = net.tran[947].outputArc;
InitArc( &parcInputs[0], 1, 885, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 936, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 967, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 967, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 902, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 936, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 948, "", 4, 2, 2, 3, 4, TF_1_3, NULL, NULL );
net.tran[948].number[1] = 3;
net.tran[948].number[2] = 18;
net.tran[948].number[3] = 3;
parcInputs = net.tran[948].inputArc;
parcOutputs = net.tran[948].outputArc;
InitArc( &parcInputs[0], 1, 886, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 967, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 963, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 967, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 902, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 963, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 893, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 949, "", 4, 0, 0, 3, 3, NULL, TE_1_4, NULL );
net.tran[949].number[1] = 3;
net.tran[949].number[2] = 18;
net.tran[949].number[3] = 4;
parcInputs = net.tran[949].inputArc;
parcOutputs = net.tran[949].outputArc;
InitArc( &parcInputs[0], 1, 962, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 933, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 911, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 873, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 911, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 896, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 950, "", 4, 0, 0, 3, 3, NULL, TE_1_5, NULL );
net.tran[950].number[1] = 3;
net.tran[950].number[2] = 18;
net.tran[950].number[3] = 5;
parcInputs = net.tran[950].inputArc;
parcOutputs = net.tran[950].outputArc;
InitArc( &parcInputs[0], 1, 907, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 966, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 936, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 885, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 936, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 903, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 951, "", 4, 0, 0, 4, 3, NULL, TE_1_6, NULL );
net.tran[951].number[1] = 3;
net.tran[951].number[2] = 18;
net.tran[951].number[3] = 6;
parcInputs = net.tran[951].inputArc;
parcOutputs = net.tran[951].outputArc;
InitArc( &parcInputs[0], 1, 907, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 966, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 933, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 962, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 886, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 903, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 896, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 952, "", 4, 2, 2, 3, 4, TF_1_7, NULL, NULL );
net.tran[952].number[1] = 3;
net.tran[952].number[2] = 18;
net.tran[952].number[3] = 7;
parcInputs = net.tran[952].inputArc;
parcOutputs = net.tran[952].outputArc;
InitArc( &parcInputs[0], 1, 887, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 967, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 963, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 967, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 900, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 963, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 892, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 953, "", 4, 2, 2, 3, 4, TF_1_8, NULL, NULL );
net.tran[953].number[1] = 3;
net.tran[953].number[2] = 18;
net.tran[953].number[3] = 8;
parcInputs = net.tran[953].inputArc;
parcOutputs = net.tran[953].outputArc;
InitArc( &parcInputs[0], 1, 891, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 967, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 963, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 967, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 900, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 963, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 889, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 954, "", 4, 0, 0, 4, 3, NULL, TE_1_9, NULL );
net.tran[954].number[1] = 3;
net.tran[954].number[2] = 18;
net.tran[954].number[3] = 9;
parcInputs = net.tran[954].inputArc;
parcOutputs = net.tran[954].outputArc;
InitArc( &parcInputs[0], 1, 907, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 965, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 933, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 888, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 887, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 903, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 896, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 955, "", 4, 0, 0, 4, 3, NULL, TE_1_10, NULL );
net.tran[955].number[1] = 3;
net.tran[955].number[2] = 18;
net.tran[955].number[3] = 10;
parcInputs = net.tran[955].inputArc;
parcOutputs = net.tran[955].outputArc;
InitArc( &parcInputs[0], 1, 907, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 965, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 933, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 961, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 891, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 903, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 896, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 956, "", 4, 0, 0, 4, 3, NULL, TE_1_11, NULL );
net.tran[956].number[1] = 3;
net.tran[956].number[2] = 18;
net.tran[956].number[3] = 11;
parcInputs = net.tran[956].inputArc;
parcOutputs = net.tran[956].outputArc;
InitArc( &parcInputs[0], 1, 907, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 964, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 933, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 888, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 969, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 903, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 896, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 957, "", 4, 2, 2, 3, 4, TF_1_12, NULL, NULL );
net.tran[957].number[1] = 3;
net.tran[957].number[2] = 18;
net.tran[957].number[3] = 12;
parcInputs = net.tran[957].inputArc;
parcOutputs = net.tran[957].outputArc;
InitArc( &parcInputs[0], 1, 969, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 967, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 963, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 967, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 898, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 963, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 892, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 958, "", 4, 0, 0, 4, 3, NULL, TE_1_13, NULL );
net.tran[958].number[1] = 3;
net.tran[958].number[2] = 18;
net.tran[958].number[3] = 13;
parcInputs = net.tran[958].inputArc;
parcOutputs = net.tran[958].outputArc;
InitArc( &parcInputs[0], 1, 907, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 964, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 933, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcInputs[3], 1, 961, 0, 1 );
parcInputs[3].color[0].var = &intersection ;
parcInputs[3].color[0].flags = COMPARE_FLAG ;
parcInputs[3].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 970, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 903, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 896, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;

InitTransition( 959, "", 4, 2, 2, 3, 4, TF_1_14, NULL, NULL );
net.tran[959].number[1] = 3;
net.tran[959].number[2] = 18;
net.tran[959].number[3] = 14;
parcInputs = net.tran[959].inputArc;
parcOutputs = net.tran[959].outputArc;
InitArc( &parcInputs[0], 1, 970, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 967, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 963, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 967, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 898, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 963, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 889, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;

InitTransition( 960, "", 4, 2, 2, 3, 4, TF_1_15, NULL, NULL );
net.tran[960].number[1] = 3;
net.tran[960].number[2] = 18;
net.tran[960].number[3] = 15;
parcInputs = net.tran[960].inputArc;
parcOutputs = net.tran[960].outputArc;
InitArc( &parcInputs[0], 1, 971, 0, 1 );
parcInputs[0].color[0].var = &intersection ;
parcInputs[0].color[0].flags = 0 ;
parcInputs[0].color[0].size = 1 ;
InitArc( &parcInputs[1], 1, 965, 0, 1 );
parcInputs[1].color[0].var = &intersection ;
parcInputs[1].color[0].flags = COMPARE_FLAG ;
parcInputs[1].color[0].size = 1 ;
InitArc( &parcInputs[2], 1, 888, 0, 1 );
parcInputs[2].color[0].var = &intersection ;
parcInputs[2].color[0].flags = COMPARE_FLAG ;
parcInputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[0], 1, 904, 0, 1 );
parcOutputs[0].color[0].var = &intersection ;
parcOutputs[0].color[0].flags = 0 ;
parcOutputs[0].color[0].size = 1 ;
InitArc( &parcOutputs[1], 1, 965, 0, 1 );
parcOutputs[1].color[0].var = &intersection ;
parcOutputs[1].color[0].flags = 0 ;
parcOutputs[1].color[0].size = 1 ;
InitArc( &parcOutputs[2], 1, 895, 0, 1 );
parcOutputs[2].color[0].var = &intersection ;
parcOutputs[2].color[0].flags = 0 ;
parcOutputs[2].color[0].size = 1 ;
InitArc( &parcOutputs[3], 1, 888, 0, 1 );
parcOutputs[3].color[0].var = &intersection ;
parcOutputs[3].color[0].flags = 0 ;
parcOutputs[3].color[0].size = 1 ;


DefineNet17();
}
#endif /* SEGMENTED_MEMORY */
#endif /* CONST_NET */

